name: build and release

on:
  workflow_dispatch:
    inputs:      
      tag:
        description: 'Release Tag'
        required: true        

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        device: [beyond2lte, beyond1lte, beyond0lte, beyondx]
        su: [non-ksu, ksu]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install packages & setup
        run: |
          sudo apt update -y  
          sudo apt install libncurses5-dev python2 libtinfo5 -y    
          git clone --depth=1 https://github.com/ravindu644/proton-12.git -b main --single-branch proton
          export PATH=$PWD/proton/bin:$PATH  
          
      - name: Set environment variable
        run: |
          echo "LPOS_KERNEL_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          
      - name: Building LPoS+NH
        run: |
          if [ "${{ matrix.su }}" == "non-ksu" ]; then
            bash build.sh ${{ matrix.device }} non-ksu
          else
            bash build.sh ${{ matrix.device }} ksu
          fi

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: "Nethunter-LPoS-${{ env.LPOS_KERNEL_VERSION }}-${{ matrix.device }}-${{ matrix.su }}-universal"
          path: |
            build/*.zip

      # Add this step to upload the universal zip file
      - name: Upload universal Kali Nethunter Drivers
        uses: actions/upload-artifact@v4
        with:
          name: "Kali-Nethunter-Drivers"
          path: "build/Kali Nethunter Drivers - Galaxy S10x [MAGISK].zip"
        # Only run this step once to avoid duplicates
        if: matrix.device == 'beyond2lte' && matrix.su == 'non-ksu'

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: "nh-${{ github.event.inputs.tag }}"
          name: "Nethunter-LPoS-${{ github.event.inputs.tag }}"
          draft: false
          prerelease: false
          token: ${{ secrets.TOKEN }}          
          artifacts: |
            artifacts/**/*.zip
            artifacts/Kali-Nethunter-Drivers/Kali Nethunter Drivers - Galaxy S10x [MAGISK].zip
          body: "Commit SHA: ${{ github.sha }}"
